---
- hosts: local
  connection: local
  gather_facts: False

  vars:
    vpc_name: "{{ lookup('env', 'VPCNAME') }}"

  vars_files:
    - "vars/{{ vpc_name }}/vault/secrets.yml"
    - "vars/{{ vpc_name }}/siteconfig.yml"
    - "vars/{{ vpc_name }}/vpc.yml"
    - "vars/{{ vpc_name }}/security_groups.yml"
    - "vars/{{ vpc_name }}/servers.yml"

  tasks:
    - include_tasks: tasks/aws-vpc/tasks/ssh_key.yml
      tags:
        - ssh_key

    - include_tasks: tasks/aws-vpc/tasks/vpc.yml
      tags:
        - vpc

    - include_tasks: tasks/aws-vpc/tasks/security_groups.yml
      tags:
        - security_groups
    
    - include_tasks: tasks/aws-vpc/tasks/iam_roles.yml
      tags:
        - iam_roles
        - iam

    - include_tasks: tasks/aws-vpc/tasks/iam_users.yml
      tags:
        - iam_users
        - iam
